\doxysection{pip.\+\_\+internal.\+exceptions.\+Pip\+Error Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1PipError}{}\label{classpip_1_1__internal_1_1exceptions_1_1PipError}\index{pip.\_internal.exceptions.PipError@{pip.\_internal.exceptions.PipError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Pip\+Error\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Pip\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}The base pip error.\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00057}{57}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
