\doxysection{pytz.\+exceptions.\+Non\+Existent\+Time\+Error Class Reference}
\hypertarget{classpytz_1_1exceptions_1_1NonExistentTimeError}{}\label{classpytz_1_1exceptions_1_1NonExistentTimeError}\index{pytz.exceptions.NonExistentTimeError@{pytz.exceptions.NonExistentTimeError}}


Inheritance diagram for pytz.\+exceptions.\+Non\+Existent\+Time\+Error\+:
% FIG 0


Collaboration diagram for pytz.\+exceptions.\+Non\+Existent\+Time\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception raised when attempting to create a wallclock time that
cannot exist.

At the start of a DST transition period, the wallclock time jumps forward.
The instants jumped over never occur.
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pytz_2exceptions_8py_source_l00053}{53}} of file \mbox{\hyperlink{pytz_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pytz/exceptions.\+py\end{DoxyCompactItemize}
