\doxysection{pip.\+\_\+internal.\+exceptions.\+Uninstallation\+Error Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1UninstallationError}{}\label{classpip_1_1__internal_1_1exceptions_1_1UninstallationError}\index{pip.\_internal.exceptions.UninstallationError@{pip.\_internal.exceptions.UninstallationError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Uninstallation\+Error\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Uninstallation\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}General exception during uninstallation\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00187}{187}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
