\doxysection{pip.\+\_\+vendor.\+pyproject\+\_\+hooks.\+\_\+in\+\_\+process.\+\_\+in\+\_\+process.\+\_\+\+Dummy\+Exception Class Reference}
\hypertarget{classpip_1_1__vendor_1_1pyproject__hooks_1_1__in__process_1_1__in__process_1_1__DummyException}{}\label{classpip_1_1__vendor_1_1pyproject__hooks_1_1__in__process_1_1__in__process_1_1__DummyException}\index{pip.\_vendor.pyproject\_hooks.\_in\_process.\_in\_process.\_DummyException@{pip.\_vendor.pyproject\_hooks.\_in\_process.\_in\_process.\_DummyException}}


Inheritance diagram for pip.\+\_\+vendor.\+pyproject\+\_\+hooks.\+\_\+in\+\_\+process.\+\_\+in\+\_\+process.\+\_\+\+Dummy\+Exception\+:
% FIG 0


Collaboration diagram for pip.\+\_\+vendor.\+pyproject\+\_\+hooks.\+\_\+in\+\_\+process.\+\_\+in\+\_\+process.\+\_\+\+Dummy\+Exception\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Nothing should ever raise this exception\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{__in__process_8py_source_l00290}{290}} of file \mbox{\hyperlink{__in__process_8py_source}{\+\_\+in\+\_\+process.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+vendor/pyproject\+\_\+hooks/\+\_\+in\+\_\+process/\+\_\+in\+\_\+process.\+py\end{DoxyCompactItemize}
