\doxysection{dateutil.\+parser.\+\_\+parser.\+Parser\+Error Class Reference}
\hypertarget{classdateutil_1_1parser_1_1__parser_1_1ParserError}{}\label{classdateutil_1_1parser_1_1__parser_1_1ParserError}\index{dateutil.parser.\_parser.ParserError@{dateutil.parser.\_parser.ParserError}}


Inheritance diagram for dateutil.\+parser.\+\_\+parser.\+Parser\+Error\+:
% FIG 0


Collaboration diagram for dateutil.\+parser.\+\_\+parser.\+Parser\+Error\+:
% FIG 1
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classdateutil_1_1parser_1_1__parser_1_1ParserError_a8d881f3a94128db01fbeaf2e6115c086}{\+\_\+\+\_\+str\+\_\+\+\_\+}} (self)
\item 
\mbox{\hyperlink{classdateutil_1_1parser_1_1__parser_1_1ParserError_a964ce0c699361bb2895228c00b6e4506}{\+\_\+\+\_\+repr\+\_\+\+\_\+}} (self)
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception subclass used for any failure to parse a datetime string.

This is a subclass of :py:exc:`ValueError`, and should be raised any time
earlier versions of ``dateutil`` would have raised ``ValueError``.

.. versionadded:: 2.8.1
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{dateutil_2parser_2__parser_8py_source_l01589}{1589}} of file \mbox{\hyperlink{dateutil_2parser_2__parser_8py_source}{\+\_\+parser.\+py}}.



\doxysubsection{Member Function Documentation}
\Hypertarget{classdateutil_1_1parser_1_1__parser_1_1ParserError_a964ce0c699361bb2895228c00b6e4506}\index{dateutil.parser.\_parser.ParserError@{dateutil.parser.\_parser.ParserError}!\_\_repr\_\_@{\_\_repr\_\_}}
\index{\_\_repr\_\_@{\_\_repr\_\_}!dateutil.parser.\_parser.ParserError@{dateutil.parser.\_parser.ParserError}}
\doxysubsubsection{\texorpdfstring{\_\_repr\_\_()}{\_\_repr\_\_()}}
{\footnotesize\ttfamily \label{classdateutil_1_1parser_1_1__parser_1_1ParserError_a964ce0c699361bb2895228c00b6e4506} 
dateutil.\+parser.\+\_\+parser.\+Parser\+Error.\+\_\+\+\_\+repr\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})}



Definition at line \mbox{\hyperlink{dateutil_2parser_2__parser_8py_source_l01603}{1603}} of file \mbox{\hyperlink{dateutil_2parser_2__parser_8py_source}{\+\_\+parser.\+py}}.

\Hypertarget{classdateutil_1_1parser_1_1__parser_1_1ParserError_a8d881f3a94128db01fbeaf2e6115c086}\index{dateutil.parser.\_parser.ParserError@{dateutil.parser.\_parser.ParserError}!\_\_str\_\_@{\_\_str\_\_}}
\index{\_\_str\_\_@{\_\_str\_\_}!dateutil.parser.\_parser.ParserError@{dateutil.parser.\_parser.ParserError}}
\doxysubsubsection{\texorpdfstring{\_\_str\_\_()}{\_\_str\_\_()}}
{\footnotesize\ttfamily \label{classdateutil_1_1parser_1_1__parser_1_1ParserError_a8d881f3a94128db01fbeaf2e6115c086} 
dateutil.\+parser.\+\_\+parser.\+Parser\+Error.\+\_\+\+\_\+str\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})}



Definition at line \mbox{\hyperlink{dateutil_2parser_2__parser_8py_source_l01597}{1597}} of file \mbox{\hyperlink{dateutil_2parser_2__parser_8py_source}{\+\_\+parser.\+py}}.



Referenced by \mbox{\hyperlink{__polybase_8py_source_l00266}{numpy.\+polynomial.\+\_\+polybase.\+ABCPoly\+Base.\+\_\+get\+\_\+coefficients()}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/dateutil/parser/\+\_\+parser.\+py\end{DoxyCompactItemize}
