\doxysection{pip.\+\_\+vendor.\+idna.\+core.\+Invalid\+Codepoint\+Context Class Reference}
\hypertarget{classpip_1_1__vendor_1_1idna_1_1core_1_1InvalidCodepointContext}{}\label{classpip_1_1__vendor_1_1idna_1_1core_1_1InvalidCodepointContext}\index{pip.\_vendor.idna.core.InvalidCodepointContext@{pip.\_vendor.idna.core.InvalidCodepointContext}}


Inheritance diagram for pip.\+\_\+vendor.\+idna.\+core.\+Invalid\+Codepoint\+Context\+:
% FIG 0


Collaboration diagram for pip.\+\_\+vendor.\+idna.\+core.\+Invalid\+Codepoint\+Context\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb} Exception when the codepoint is not valid in the context it is used \end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__vendor_2idna_2core_8py_source_l00027}{27}} of file \mbox{\hyperlink{pip_2__vendor_2idna_2core_8py_source}{core.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+vendor/idna/core.\+py\end{DoxyCompactItemize}
