\doxysection{pandas.\+errors.\+Numba\+Util\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1NumbaUtilError}{}\label{classpandas_1_1errors_1_1NumbaUtilError}\index{pandas.errors.NumbaUtilError@{pandas.errors.NumbaUtilError}}


Inheritance diagram for pandas.\+errors.\+Numba\+Util\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Numba\+Util\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Error raised for unsupported Numba engine routines.

Examples
--------
>>> df = pd.DataFrame({"key": ["a", "a", "b", "b"], "data": [1, 2, 3, 4]},
...                   columns=["key", "data"])
>>> def incorrect_function(x):
...     return sum(x) * 2.7
>>> df.groupby("key").agg(incorrect_function, engine="numba")
Traceback (most recent call last):
NumbaUtilError: The first 2 arguments to incorrect_function
must be ['values', 'index']
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00311}{311}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
