\doxysection{pandas.\+errors.\+Data\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1DataError}{}\label{classpandas_1_1errors_1_1DataError}\index{pandas.errors.DataError@{pandas.errors.DataError}}


Inheritance diagram for pandas.\+errors.\+Data\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Data\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exceptionn raised when performing an operation on non-numerical data.

For example, calling ``ohlc`` on a non-numerical column or a function
on a rolling window.

Examples
--------
>>> ser = pd.Series(['a', 'b', 'c'])
>>> ser.rolling(2).sum()
Traceback (most recent call last):
DataError: No numeric types to aggregate
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00367}{367}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
