\doxysection{pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashMismatch}{}\label{classpip_1_1__internal_1_1exceptions_1_1HashMismatch}\index{pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch\+:
% FIG 1
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
None \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a89b96c614c9c81ba7b4ecd23e51c8a30}{\+\_\+\+\_\+init\+\_\+\+\_\+}} (self, Dict\mbox{[}str, List\mbox{[}str\mbox{]}\mbox{]} allowed, Dict\mbox{[}str, "{}\+\_\+\+Hash"{}\mbox{]} gots)
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a24c9ffc7b9a48c74ac53439d56a05dc6}{body}} (self)
\end{DoxyCompactItemize}
\doxysubsection*{Public Member Functions inherited from \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError}{pip.\+\_\+internal.\+exceptions.\+Hash\+Error}}}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a455e73a1648e11e2d124cf5bd30f97f3}{\+\_\+\+\_\+str\+\_\+\+\_\+}} (self)
\end{DoxyCompactItemize}
\doxysubsubsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a75f1e4930d8d7dca662cfa12bd05842f}{allowed}} = allowed
\item 
\mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_abae5463ebcc1108c4695cad4065133ce}{gots}} = gots
\end{DoxyCompactItemize}
\doxysubsubsection*{Protected Member Functions}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a9b7e5755035de0fc7149dcae9e18346a}{\+\_\+hash\+\_\+comparison}} (self)
\end{DoxyCompactItemize}
\doxysubsection*{Protected Member Functions inherited from \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError}{pip.\+\_\+internal.\+exceptions.\+Hash\+Error}}}
\begin{DoxyCompactItemize}
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a17be3100accef085731b0299b3528866}{\+\_\+requirement\+\_\+name}} (self)
\end{DoxyCompactItemize}
\doxysubsubsection*{Additional Inherited Members}
\doxysubsection*{Static Public Attributes inherited from \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError}{pip.\+\_\+internal.\+exceptions.\+Hash\+Error}}}
\begin{DoxyCompactItemize}
\item 
Optional \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_af3c50ea4f7da6636a64b938cda7052c9}{req}} = None
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_ad051d7f7e98b51e235a5bc4ca17b302c}{head}} = "{}"{}
\item 
int \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a81cbe1b130a39b1625d11456709e1047}{order}} = -\/1
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Distribution file hash values don't match.

:ivar package_name: The name of the package that triggered the hash
    mismatch. Feel free to write to this after the exception is raise to
    improve its error message.
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00565}{565}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



\doxysubsection{Constructor \& Destructor Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a89b96c614c9c81ba7b4ecd23e51c8a30}\index{pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}!\_\_init\_\_@{\_\_init\_\_}}
\index{\_\_init\_\_@{\_\_init\_\_}!pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}}
\doxysubsubsection{\texorpdfstring{\_\_init\_\_()}{\_\_init\_\_()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a89b96c614c9c81ba7b4ecd23e51c8a30} 
 None pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch.\+\_\+\+\_\+init\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self}{, }\item[{Dict\mbox{[}str, List\mbox{[}str\mbox{]}\mbox{]}}]{allowed}{, }\item[{Dict\mbox{[}str, "{}\+\_\+\+Hash"{}\mbox{]}}]{gots}{}\end{DoxyParamCaption})}

\begin{DoxyVerb}:param allowed: A dict of algorithm names pointing to lists of allowed
    hex digests
:param gots: A dict of algorithm names pointing to hashes we
    actually got from the files under suspicion
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00583}{583}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



Referenced by \mbox{\hyperlink{kernels_8py_source_l00178}{sklearn.\+gaussian\+\_\+process.\+kernels.\+Kernel.\+get\+\_\+params()}}, and \mbox{\hyperlink{__distn__infrastructure_8py_source_l00643}{scipy.\+stats.\+\_\+distn\+\_\+infrastructure.\+rv\+\_\+generic.\+random\+\_\+state()}}.



\doxysubsection{Member Function Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a9b7e5755035de0fc7149dcae9e18346a}\index{pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}!\_hash\_comparison@{\_hash\_comparison}}
\index{\_hash\_comparison@{\_hash\_comparison}!pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}}
\doxysubsubsection{\texorpdfstring{\_hash\_comparison()}{\_hash\_comparison()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a9b7e5755035de0fc7149dcae9e18346a} 
 str pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch.\+\_\+hash\+\_\+comparison (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [protected]}}

\begin{DoxyVerb}Return a comparison of actual and expected hash values.

Example::

       Expected sha256 abcdeabcdeabcdeabcdeabcdeabcdeabcdeabcdeabcde
                    or 123451234512345123451234512345123451234512345
            Got        bcdefbcdefbcdefbcdefbcdefbcdefbcdefbcdefbcdef
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00596}{596}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a24c9ffc7b9a48c74ac53439d56a05dc6}\index{pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}!body@{body}}
\index{body@{body}!pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}}
\doxysubsubsection{\texorpdfstring{body()}{body()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a24c9ffc7b9a48c74ac53439d56a05dc6} 
 str pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch.\+body (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})}

\begin{DoxyVerb}Return a summary of me for display under the heading.

This default implementation simply prints a description of the
triggering requirement.

:param req: The InstallRequirement that provoked this error, with
    its link already populated by the resolver's _populate_link().
\end{DoxyVerb}
 

Reimplemented from \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1HashError_a8b1a0890122218544dd1a3e23c416431}{pip.\+\_\+internal.\+exceptions.\+Hash\+Error}}.



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00593}{593}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



\doxysubsection{Member Data Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a75f1e4930d8d7dca662cfa12bd05842f}\index{pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}!allowed@{allowed}}
\index{allowed@{allowed}!pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}}
\doxysubsubsection{\texorpdfstring{allowed}{allowed}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_a75f1e4930d8d7dca662cfa12bd05842f} 
pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch.\+allowed = allowed}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00590}{590}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_abae5463ebcc1108c4695cad4065133ce}\index{pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}!gots@{gots}}
\index{gots@{gots}!pip.\_internal.exceptions.HashMismatch@{pip.\_internal.exceptions.HashMismatch}}
\doxysubsubsection{\texorpdfstring{gots}{gots}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1HashMismatch_abae5463ebcc1108c4695cad4065133ce} 
pip.\+\_\+internal.\+exceptions.\+Hash\+Mismatch.\+gots = gots}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00591}{591}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
