\doxysection{pip.\+\_\+internal.\+exceptions.\+None\+Metadata\+Error Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError}{}\label{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError}\index{pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+None\+Metadata\+Error\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+None\+Metadata\+Error\+:
% FIG 1
\doxysubsubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
None \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_aea5de65c8dd60ba87ed2e63b3e1226b7}{\+\_\+\+\_\+init\+\_\+\+\_\+}} (self, "{}Base\+Distribution"{} dist, str metadata\+\_\+name)
\item 
str \mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_a98590571e303910c6bffb57bddba2d36}{\+\_\+\+\_\+str\+\_\+\+\_\+}} (self)
\end{DoxyCompactItemize}
\doxysubsubsection*{Public Attributes}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_abb15dea81454b2d82a0bd4460aeb47f5}{dist}} = dist
\item 
\mbox{\hyperlink{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_a481999145818b3f67f84c05fde8ab1eb}{metadata\+\_\+name}} = metadata\+\_\+name
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when accessing a Distribution's "METADATA" or "PKG-INFO".

This signifies an inconsistency, when the Distribution claims to have
the metadata file (if not, raise ``FileNotFoundError`` instead), but is
not actually able to produce its content. This may be due to permission
errors.
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00225}{225}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



\doxysubsection{Constructor \& Destructor Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_aea5de65c8dd60ba87ed2e63b3e1226b7}\index{pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}!\_\_init\_\_@{\_\_init\_\_}}
\index{\_\_init\_\_@{\_\_init\_\_}!pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}}
\doxysubsubsection{\texorpdfstring{\_\_init\_\_()}{\_\_init\_\_()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_aea5de65c8dd60ba87ed2e63b3e1226b7} 
 None pip.\+\_\+internal.\+exceptions.\+None\+Metadata\+Error.\+\_\+\+\_\+init\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self}{, }\item[{"{}Base\+Distribution"{}}]{dist}{, }\item[{str}]{metadata\+\_\+name}{}\end{DoxyParamCaption})}

\begin{DoxyVerb}:param dist: A Distribution object.
:param metadata_name: The name of the metadata being accessed
    (can be "METADATA" or "PKG-INFO").
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00234}{234}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



References \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00244}{dist}}, and \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00245}{metadata\+\_\+name}}.



Referenced by \mbox{\hyperlink{kernels_8py_source_l00178}{sklearn.\+gaussian\+\_\+process.\+kernels.\+Kernel.\+get\+\_\+params()}}, and \mbox{\hyperlink{__distn__infrastructure_8py_source_l00643}{scipy.\+stats.\+\_\+distn\+\_\+infrastructure.\+rv\+\_\+generic.\+random\+\_\+state()}}.



\doxysubsection{Member Function Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_a98590571e303910c6bffb57bddba2d36}\index{pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}!\_\_str\_\_@{\_\_str\_\_}}
\index{\_\_str\_\_@{\_\_str\_\_}!pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}}
\doxysubsubsection{\texorpdfstring{\_\_str\_\_()}{\_\_str\_\_()}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_a98590571e303910c6bffb57bddba2d36} 
 str pip.\+\_\+internal.\+exceptions.\+None\+Metadata\+Error.\+\_\+\+\_\+str\+\_\+\+\_\+ (\begin{DoxyParamCaption}\item[{}]{self}{}\end{DoxyParamCaption})}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00247}{247}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



\doxysubsection{Member Data Documentation}
\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_abb15dea81454b2d82a0bd4460aeb47f5}\index{pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}!dist@{dist}}
\index{dist@{dist}!pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}}
\doxysubsubsection{\texorpdfstring{dist}{dist}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_abb15dea81454b2d82a0bd4460aeb47f5} 
pip.\+\_\+internal.\+exceptions.\+None\+Metadata\+Error.\+dist = dist}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00244}{244}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



Referenced by \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00238}{\+\_\+\+\_\+init\+\_\+\+\_\+()}}, \mbox{\hyperlink{candidates_8py_source_l00203}{pip.\+\_\+internal.\+resolution.\+resolvelib.\+candidates.\+\_\+\+Install\+Requirement\+Backed\+Candidate.\+\_\+check\+\_\+metadata\+\_\+consistency()}}, \mbox{\hyperlink{candidates_8py_source_l00184}{pip.\+\_\+internal.\+resolution.\+resolvelib.\+candidates.\+\_\+\+Install\+Requirement\+Backed\+Candidate.\+name()}}, \mbox{\hyperlink{candidates_8py_source_l00369}{pip.\+\_\+internal.\+resolution.\+resolvelib.\+candidates.\+Already\+Installed\+Candidate.\+name()}}, \mbox{\hyperlink{candidates_8py_source_l00177}{pip.\+\_\+internal.\+resolution.\+resolvelib.\+candidates.\+\_\+\+Install\+Requirement\+Backed\+Candidate.\+project\+\_\+name()}}, and \mbox{\hyperlink{candidates_8py_source_l00365}{pip.\+\_\+internal.\+resolution.\+resolvelib.\+candidates.\+Already\+Installed\+Candidate.\+project\+\_\+name()}}.

\Hypertarget{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_a481999145818b3f67f84c05fde8ab1eb}\index{pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}!metadata\_name@{metadata\_name}}
\index{metadata\_name@{metadata\_name}!pip.\_internal.exceptions.NoneMetadataError@{pip.\_internal.exceptions.NoneMetadataError}}
\doxysubsubsection{\texorpdfstring{metadata\_name}{metadata\_name}}
{\footnotesize\ttfamily \label{classpip_1_1__internal_1_1exceptions_1_1NoneMetadataError_a481999145818b3f67f84c05fde8ab1eb} 
pip.\+\_\+internal.\+exceptions.\+None\+Metadata\+Error.\+metadata\+\_\+name = metadata\+\_\+name}



Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00245}{245}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



Referenced by \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00238}{\+\_\+\+\_\+init\+\_\+\+\_\+()}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
