\doxysection{pytz.\+exceptions.\+Ambiguous\+Time\+Error Class Reference}
\hypertarget{classpytz_1_1exceptions_1_1AmbiguousTimeError}{}\label{classpytz_1_1exceptions_1_1AmbiguousTimeError}\index{pytz.exceptions.AmbiguousTimeError@{pytz.exceptions.AmbiguousTimeError}}


Inheritance diagram for pytz.\+exceptions.\+Ambiguous\+Time\+Error\+:
% FIG 0


Collaboration diagram for pytz.\+exceptions.\+Ambiguous\+Time\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception raised when attempting to create an ambiguous wallclock time.

At the end of a DST transition period, a particular wallclock time will
occur twice (once before the clocks are set back, once after). Both
possibilities may be correct, unless further information is supplied.

See DstTzInfo.normalize() for more info
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pytz_2exceptions_8py_source_l00042}{42}} of file \mbox{\hyperlink{pytz_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pytz/exceptions.\+py\end{DoxyCompactItemize}
