\doxysection{pandas.\+errors.\+Lossy\+Setitem\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1LossySetitemError}{}\label{classpandas_1_1errors_1_1LossySetitemError}\index{pandas.errors.LossySetitemError@{pandas.errors.LossySetitemError}}


Inheritance diagram for pandas.\+errors.\+Lossy\+Setitem\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Lossy\+Setitem\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when trying to do a __setitem__ on an np.ndarray that is not lossless.

Notes
-----
This is an internal error.
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00783}{783}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
