\doxysection{pip.\+\_\+internal.\+exceptions.\+Previous\+Build\+Dir\+Error Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1PreviousBuildDirError}{}\label{classpip_1_1__internal_1_1exceptions_1_1PreviousBuildDirError}\index{pip.\_internal.exceptions.PreviousBuildDirError@{pip.\_internal.exceptions.PreviousBuildDirError}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Previous\+Build\+Dir\+Error\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Previous\+Build\+Dir\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raised when there's a previous conflicting build directory\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00287}{287}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
