\doxysection{scipy.\+special.\+\_\+sf\+\_\+error.\+Special\+Function\+Error Class Reference}
\hypertarget{classscipy_1_1special_1_1__sf__error_1_1SpecialFunctionError}{}\label{classscipy_1_1special_1_1__sf__error_1_1SpecialFunctionError}\index{scipy.special.\_sf\_error.SpecialFunctionError@{scipy.special.\_sf\_error.SpecialFunctionError}}


Inheritance diagram for scipy.\+special.\+\_\+sf\+\_\+error.\+Special\+Function\+Error\+:
% FIG 0


Collaboration diagram for scipy.\+special.\+\_\+sf\+\_\+error.\+Special\+Function\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception that can be raised by special functions.\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{__sf__error_8py_source_l00013}{13}} of file \mbox{\hyperlink{__sf__error_8py_source}{\+\_\+sf\+\_\+error.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/scipy/special/\+\_\+sf\+\_\+error.\+py\end{DoxyCompactItemize}
