\doxysection{pandas.\+errors.\+Invalid\+Index\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1InvalidIndexError}{}\label{classpandas_1_1errors_1_1InvalidIndexError}\index{pandas.errors.InvalidIndexError@{pandas.errors.InvalidIndexError}}


Inheritance diagram for pandas.\+errors.\+Invalid\+Index\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Invalid\+Index\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Exception raised when attempting to use an invalid index key.

Examples
--------
>>> idx = pd.MultiIndex.from_product([["x", "y"], [0, 1]])
>>> df = pd.DataFrame([[1, 1, 2, 2],
...                   [3, 3, 4, 4]], columns=idx)
>>> df
    x       y
    0   1   0   1
0   1   1   2   2
1   3   3   4   4
>>> df[:, 0]
Traceback (most recent call last):
InvalidIndexError: (slice(None, None, None), 0)
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00347}{347}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
