\doxysection{pip.\+\_\+internal.\+exceptions.\+Unsupported\+Python\+Version Class Reference}
\hypertarget{classpip_1_1__internal_1_1exceptions_1_1UnsupportedPythonVersion}{}\label{classpip_1_1__internal_1_1exceptions_1_1UnsupportedPythonVersion}\index{pip.\_internal.exceptions.UnsupportedPythonVersion@{pip.\_internal.exceptions.UnsupportedPythonVersion}}


Inheritance diagram for pip.\+\_\+internal.\+exceptions.\+Unsupported\+Python\+Version\+:
% FIG 0


Collaboration diagram for pip.\+\_\+internal.\+exceptions.\+Unsupported\+Python\+Version\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Unsupported python version according to Requires-Python package
metadata.\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source_l00623}{623}} of file \mbox{\hyperlink{pip_2__internal_2exceptions_8py_source}{exceptions.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pip/\+\_\+internal/exceptions.\+py\end{DoxyCompactItemize}
