\doxysection{pandas.\+errors.\+Duplicate\+Label\+Error Class Reference}
\hypertarget{classpandas_1_1errors_1_1DuplicateLabelError}{}\label{classpandas_1_1errors_1_1DuplicateLabelError}\index{pandas.errors.DuplicateLabelError@{pandas.errors.DuplicateLabelError}}


Inheritance diagram for pandas.\+errors.\+Duplicate\+Label\+Error\+:
% FIG 0


Collaboration diagram for pandas.\+errors.\+Duplicate\+Label\+Error\+:
% FIG 1


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Error raised when an operation would introduce duplicate labels.

Examples
--------
>>> s = pd.Series([0, 1, 2], index=['a', 'b', 'c']).set_flags(
...     allows_duplicate_labels=False
... )
>>> s.reindex(['a', 'a', 'b'])
Traceback (most recent call last):
   ...
DuplicateLabelError: Index has duplicates.
      positions
label
a        [0, 1]
\end{DoxyVerb}
 

Definition at line \mbox{\hyperlink{pandas_2errors_2____init_____8py_source_l00328}{328}} of file \mbox{\hyperlink{pandas_2errors_2____init_____8py_source}{\+\_\+\+\_\+init\+\_\+\+\_\+.\+py}}.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
/home/jam/\+Research/\+IRES-\/2025/dev/src/llm-\/scripts/testing/hypothesis-\/testing/hyp-\/env/lib/python3.\+12/site-\/packages/pandas/errors/\+\_\+\+\_\+init\+\_\+\+\_\+.\+py\end{DoxyCompactItemize}
